### ISSUE TITLE
Does not work on POP OS 22.04 (built mpv from source)

### ISSUE THREAD

**Issue by hhacker1999** [iwalton3/plex-mpv-shim#71]
2022-05-07 16:19:10,892 [    INFO] conf: Loaded settings from json: /home/harsh/.config/plex-mpv-shim/conf.json
2022-05-07 16:19:11,001 [ WARNING] root: Cannot load GUI. Falling back to command line interface.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pystray/_appindicator.py", line 23, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/mpv_shim.py", line 39, in main
    from .gui_mgr import userInterface
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/gui_mgr.py", line 1, in <module>
    from pystray import Icon, MenuItem, Menu
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 62, in <module>
    Icon = backend().Icon
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 54, in backend
    return candidate()
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 26, in appindicator
    from . import _appindicator as backend; return backend
  File "/usr/local/lib/python3.10/dist-packages/pystray/_appindicator.py", line 26, in <module>
    gi.require_version('AyatanaAppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available
2022-05-07 16:19:11,069 [    INFO] player: Using libmpv1 playback backend.
Traceback (most recent call last):
  File "/usr/local/bin/plex-mpv-shim", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/mpv_shim.py", line 47, in main
    from .player import playerManager
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/player.py", line 568, in <module>
    playerManager = PlayerManager()
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/player.py", line 235, in __init__
    def handle_end_idle(event):
  File "/usr/local/lib/python3.10/dist-packages/mpv.py", line 1606, in register
    types = [MpvEventID.from_str(t) if isinstance(t, str) else t for t in event_types] or MpvEventID.ANY
  File "/usr/local/lib/python3.10/dist-packages/mpv.py", line 1606, in <listcomp>
    types = [MpvEventID.from_str(t) if isinstance(t, str) else t for t in event_types] or MpvEventID.ANY
  File "/usr/local/lib/python3.10/dist-packages/mpv.py", line 299, in from_str
    return getattr(kls, s.upper().replace('-', '_'))
AttributeError: type object 'MpvEventID' has no attribute 'IDLE'

**Comment by iwalton3** [comment]
Try using an older MPV version or use external MPV mode.

**Comment by swazrgb** [comment]
Caused by #72
